import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import { SessionProvider } from 'next-auth/react';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${cn(
					'min-h-screen font-sans w-full h-auto',
					fontSans.variable
				)} bg-[#050B22] bg-svg-pattern bg-cover`}
			>
				<SessionProvider>
					<div id="modal-root"></div>
					{children}
				</SessionProvider>
			</body>
		</html>
	);
}
