import type { Metadata } from 'next';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import MainApp from './MainApp';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<SessionProvider>
				<MainApp>{children}</MainApp>=
			</SessionProvider>
		</html>
	);
}
